# config/packages/security.yaml

security:
    # ==================================
    # Passwort-Hashing
    # ==================================
    password_hashers:
        App\Entity\User: 'auto'

    # ==================================
    # Benutzer- & API-Key-Provider
    # ==================================
    providers:
        api_key_provider:
            id: App\Repository\ApiKeyRepository

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        # Chain-Provider kombiniert API-Key und User-Provider
        chain_provider:
            chain:
                providers: [api_key_provider, app_user_provider]

    # ==================================
    # Firewalls
    # ==================================
    firewalls:
        # Dev-Firewall (Profiler, Assets)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Login-Firewall für JWT-Login
        login:
            pattern: ^/api/login_check
            stateless: true
            provider: app_user_provider
            json_login:
                check_path:       /api/login_check
                username_path:    email
                password_path:    password
                success_handler:  lexik_jwt_authentication.handler.authentication_success
                failure_handler:  lexik_jwt_authentication.handler.authentication_failure

        # Haupt-Firewall für alle API-Routen
        api:
            pattern:   ^/api
            stateless: true
            provider:  chain_provider

            # JWT-Authentifizierung via LexikJWT
            jwt: ~

            # API-Key-Authentifizierung
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator

        # (Optional) klassische Web-UI
        main:
            lazy: true
            provider: app_user_provider

    # ==================================
    # Zugriffskontrolle
    # ==================================
    access_control:
        # Anonymen Login erlauben
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Andere API-Endpunkte erfordern Authentifizierung
        - { path: ^/api,            roles: IS_AUTHENTICATED_FULLY }
