# config/packages/security.yaml

security:
    # ==================================
    # Passwort-Hashing (für evtl. App-User)
    # ==================================
    password_hashers:
        App\Entity\User: 'auto'

    # ==================================
    # Benutzer- & API-Key-Provider
    # ==================================
    providers:
        # Wir verwenden als einzigen Provider unseren ApiKeyUserProvider
        api_key_provider:
            id: App\Security\ApiKeyUserProvider

    # ==================================
    # Firewalls
    # ==================================
    firewalls:
        # Dev-Firewall (Profiler, Assets)
        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false

        # Haupt-Firewall für alle API-Routen
        api:
            pattern:   ^/api
            stateless: true
            provider:  api_key_provider

            # Nur unser API-Key-Authenticator
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator

        # (Optional) klassische Web-UI / andere Bereiche
        main:
            lazy:     true
            provider: api_key_provider

    # ==================================
    # Zugriffskontrolle
    # ==================================
    access_control:
        # Alles unter /api erfordert ROLE_API (via X-API-KEY)
        - { path: ^/api, roles: ROLE_API }
